[package]
name = "xivotp"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.15", features = ["json", "blocking"] }
tokio = { version = "1", features = ["full"] }
log = "0.4"
env_logger = "0.10"
totp-rs = "^5.0"
clap = { version = "4.5.38", features = ["derive"] }
